version: "3"
services:
  web:
    image: jax:1.0.0
    depends_on:
      - db
      - taskmanager
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - "9999:9999"
    volumes:
      - web-data:/app/jax/jar_dir
    networks:
      - jax
  taskmanager:
    image: ${FLINK_IMAGE:-flink:1.9.1-scala_2.11}
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    networks:
      - jax
  jobmanager:
    image: ${FLINK_IMAGE:-flink:1.9.1-scala_2.11}
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    ports:
      - "8081:8081"
    networks:
      - jax
  db:
    image: mysql:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: jax_db
    ports:
      - "23306:3306"
    networks:
      - jax
    volumes:
      - db-data:/var/lib/mysql
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - jax
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_AD_IP:-192.168.51.124}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: sourceTopic:2:1,sinkTopic:2:1
    networks:
      - jax
  kafka-manager:
    image: sheepkiller/kafka-manager
    command: -Dpidfile.path=/dev/null
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    networks:
      - jax

networks:
  jax:

volumes:
  db-data:
  web-data: